### Create a NumPy array and perform various operations like +, -, *, and /

In [3]:
import numpy as np

In [39]:
array1 = np.array([10, 20, 30, 40])
array2 = np.array([[1, 2, 3, 4 ], [9, 4, 5, 6]])

In [40]:
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Addition: ", addition)
print("\nSubtraction: ", subtraction)
print("\nMultiplication: ", multiplication)
print("\nDivision: ", division)

Addition:  [[11 22 33 44]
 [19 24 35 46]]

Subtraction:  [[ 9 18 27 36]
 [ 1 16 25 34]]

Multiplication:  [[ 10  40  90 160]
 [ 90  80 150 240]]

Division:  [[10.         10.         10.         10.        ]
 [ 1.11111111  5.          6.          6.66666667]]


### Explore indexing and slicing

In [41]:
# Indexing: Access 3rd element
print("Access 3rd element:      ", array1[2])

#Slicing: Slice from index 1 to 3
print("Slice from index 1 to 3: ", array2[1, 1])

Access 3rd element:       30
Slice from index 1 to 3:  4


### Reshaping arrays and Transposing matrices

In [50]:
# 4. Reshaping 
reshaped = array2.reshape(4, 2)
print("Reshape Array: ", reshaped)

# transposing
transposed = array2.T
print("\nTransposed Array: ", transposed)

Reshape Array:  [[1 2]
 [3 4]
 [9 4]
 [5 6]]

Transposed Array:  [[1 9]
 [2 4]
 [3 5]
 [4 6]]


### NumPy functions to calculate statistics like mean, median, standard deviation, and variance

In [52]:
mean = np.mean(array2)
median = np.median(array2)
std_dev = np.std(array2)
variance = np.var(array2)

print("Mean: ", mean)
print("Median: ", median)
print("Standard Deviation: ", std_dev)
print("Variance: ", variance)

Mean:  4.25
Median:  4.0
Standard Deviation:  2.331844763272204
Variance:  5.4375


### Create arrays with different data types (e.g., int, float, bool, str)

In [62]:
int_array = np.array([1, 2, 3], dtype=int)
float_array = np.array([1.1, 2.2, 3.3], dtype=float)
bool_array = np.array([True, False, True], dtype=bool)
str_array = np.array(['a', 'b', 'c'], dtype=str)

print("Integer Data type: ", int_array.dtype)
print("Float Data type: ",float_array.dtype)
print("Boolean Data type: ",bool_array.dtype)
print("String Data type: ",str_array.dtype)

Integer Data type:  int32
Float Data type:  float64
Boolean Data type:  bool
String Data type:  <U1


### Concatenate arrays

In [67]:
concatenated = np.concatenate((array1, np.array([7, 8, 9, 1])))

print("Concatenated Array: ", concatenated)

Concatenated Array:  [10 20 30 40  7  8  9  1]


### Sort arrays in ascending or descending order

In [71]:
sorted_asc = np.sort(concatenated)
sorted_desc = np.sort(concatenated)[::-1]


print("Sorted Ascending: ", sorted_asc)
print("Sorted Descending: ", sorted_desc)

Sorted Ascending:  [ 1  7  8  9 10 20 30 40]
Sorted Descending:  [40 30 20 10  9  8  7  1]
